// Generated by CoffeeScript 1.10.0
var assign_style, author, awardMedals, bitlist, body, changeNumbers, click_object, contenders, courses, css_maps, cubes, current_year, date, dish, display_happy_message, display_message, double, favorit_num, food, foods, friend, gold, grade, happy_message, html, i, inner, j, k, kids, l, len, len1, len2, len3, list, math, mobyDick, mood, my_hobby, n, num, number, opposite, outer, quote, race, ref, rest, score, see_year, see_year_is_2015, sentence, show_tab, silver, singers, singersong_writer, square, tab_menu_handle, triple,
  slice = [].slice;

current_year = 2015;

happy_message = "올 " + current_year + "한해는 모두 행복";

see_year_is_2015 = current_year === 2015 ? true : false;

if (see_year_is_2015) {
  singersong_writer = happy_message;
}

if (current_year === 2015) {
  singersong_writer = happy_message;
}

if (current_year !== 2015) {
  singersong_writer = happy_message;
}

singersong_writer = current_year !== 2015 ? happy_message : void 0;

display_message = function() {
  return happy_message;
};

display_message();

display_message();

display_happy_message = function(message) {
  if (message == null) {
    message = '안녕하세요';
  }
  return message;
};

see_year = 2015;

display_happy_message(see_year);


/*
 jQuery + cofeescript
 */

document.ready = function() {
  return $this.addClass('body-l');
};

body = document.body;

$(body).ready(function() {
  if ((body != null) && (typeof html !== "undefined" && html !== null)) {
    return this.addClass('body-l');
  } else {
    return this.removeClass('body-l');
  }
});

favorit_num = [1, 2, 3, 4, 5];

bitlist = [1, 0, 1, 0, 0, 1, 1, 1, 0];

my_hobby = [football, reading, book];

singers = {
  Jagger: "Rock",
  Elvis: "Roll"
};

friend = {
  jan: {
    name: jan,
    jender: man
  },
  kai: {
    name: kai,
    jender: man
  },
  lia: {
    name: lia,
    jender: woman
  }
};

kids = {
  brother: {
    name: "Max",
    age: 11
  },
  sister: {
    name: "Ida",
    age: 9
  }
};

score = 44;

grade = (function() {
  switch (score) {
    case score <= 100:
      return message('A+');
    case score <= 90:
      return message('A');
    case score <= 80:
      return message('B+');
    case score <= 70:
      return message('B');
    case score <= 60:
      return message('C+');
    case score <= 50:
      return message('C');
    default:
      return message('F');
  }
})();

tab_menu_handle = jQuerytabs.find(a);

show_tab = function(target) {
  var handle, j, len, results;
  results = [];
  for (j = 0, len = tab_menu_handle.length; j < len; j++) {
    handle = tab_menu_handle[j];
    results.push($(handle).click());
  }
  return results;
};

css_maps = {
  'color': 'tan',
  'background-color': 'snow',
  'font-size': '14px',
  'font-weight': 100
};

assign_style = function(prop) {
  var element;
  element = document.body;
  element.style(prop);
};

number = 42;

opposite = true;

if (opposite) {
  number = -42;
}

if (opposite) {
  number = -42;
}

if (opposite) {
  number = -42;
}

if (!test) {
  number = -20;
}

if (!test) {
  number = -20;
}

if (!test) {
  number = -20;
}

square = function(x) {
  return x * x;
};

double = function(m) {
  return m * m;
};

triple = function(m) {
  return double(m) * m;
};

list = [1, 2, 3, 4, 5];

math = {
  root: Math.sqrt,
  square: square,
  cube: function(x) {
    return x * square(x);
  }
};

race = function() {
  var runners, winner;
  winner = arguments[0], runners = 2 <= arguments.length ? slice.call(arguments, 1) : [];
  return print(winner, runners);
};

click_object = function() {
  var arg1, arg2, args;
  arg1 = arguments[0], arg2 = arguments[1], args = 3 <= arguments.length ? slice.call(arguments, 2) : [];
  return console.log(arg1, arg2);
};

if (typeof elvis !== "undefined" && elvis !== null) {
  alert("I knew it!");
}

cubes = (function() {
  var j, len, results;
  results = [];
  for (j = 0, len = list.length; j < len; j++) {
    num = list[j];
    results.push(math.cube(num));
  }
  return results;
})();

for (j = 0, len = list.length; j < len; j++) {
  num = list[j];
  cubes = math.cube(num);
}

(function(global, $) {
  'use strict';
})(window, window.jQuery);

author = "Wittgenstein";

quote = "A picture is a fact. -- " + author;

sentence = (22 / 7) + " is a decent approximation of π";

mobyDick = "Call me Ishmael. Some years ago -- never mind how long precisely -- having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world...";

html = "<strong>\n  cup of \n  coffeescript\n</strong>";


/*
주석
SkinnyMochaHalfCaffScript Compiler v1.0
Released under the MIT License
 */

outer = 1;

changeNumbers = function() {
  var inner;
  inner = -1;
  return outer = 10;
};

inner = changeNumbers();

if (singing) {
  mood = greatlyImproved;
}

if (happy && knowsIt) {
  clapsHands();
  chaChaCha();
} else {
  showIt();
}

date = friday ? sue : jill;

gold = silver = rest = "unknown";

awardMedals = function() {
  var first, others, second;
  first = arguments[0], second = arguments[1], others = 3 <= arguments.length ? slice.call(arguments, 2) : [];
  gold = first;
  silver = second;
  return rest = others;
};

contenders = ["Michael Phelps", "Liu Xiang", "Yao Ming", "Allyson Felix", "Shawn Johnson", "Roman Sebrle", "Guo Jingjing", "Tyson Gay", "Asafa Powell", "Usain Bolt"];

awardMedals.apply(null, contenders);

alert("Gold: " + gold);

alert("Silver: " + silver);

alert("The Field: " + rest);

ref = ['toast', 'cheese', 'wine'];
for (k = 0, len1 = ref.length; k < len1; k++) {
  food = ref[k];
  eat(food);
}

courses = ['greens', 'caviar', 'truffles', 'roast', 'cake'];

for (i = l = 0, len2 = courses.length; l < len2; i = ++l) {
  dish = courses[i];
  menu(i + 1, dish);
}

foods = ['broccoli', 'spinach', 'chocolate'];

for (n = 0, len3 = foods.length; n < len3; n++) {
  food = foods[n];
  if (food !== 'chocolate') {
    eat(food);
  }
}
